services:
  vini-restream:

    image: ghcr.io/ardoviniandrea/vini-restream:latest
    ports:
      # 8995 for the UI (proxied by Nginx)
      - "8995:8995"
      # 8994 for the HLS Stream (served by Nginx)
      - "8994:8994"
    restart: unless-stopped
