services:
  vini-restream:
    container_name: vini-restream
    image: ghcr.io/ardoviniandrea/vini-restream:latest
    ports:
      # 8995 for the UI (proxied by Nginx)
      - "8995:8995"
      # 8994 for the HLS Stream (served by Nginx)
      - "8994:8994"
    restart: unless-stopped
    # --- NEW: Add persistent volume mount ---
    # Mounts the 'restream-data' volume to the '/data' directory in the container.
    # This is where we will store the SQLite database.
    volumes:
      - restream-data:/data

# --- NEW: Define the named volume ---
# This tells Docker to manage a persistent volume named 'restream-data'.
volumes:
  restream-data:
